# No idea why, but any optimization level breaks the solution

solution: algos.cpp args.cpp main.cpp state_space.cpp utils.cpp
	g++ -o solution algos.cpp args.cpp main.cpp state_space.cpp utils.cpp

clean:
	rm -f solution
